backend:
  name: github
  repo: nhlocal/blog # ודא שזה שם המשתמש והרפוזיטורי שלך
  branch: jekyll # או master, תלוי בענף הראשי שלך
  auth_type: implicit # <-- הוספנו את השורה הזו
  app_id: Ov23liVTGo8G9ClPRL1H  # <-- הוספנו את השורה הזו. יש להחליף את הטקסט!

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "פוסטים"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "כותרת", name: "title", widget: "string", required: true }
      - { label: "תאריך פרסום", name: "date", widget: "datetime", required: true }
      - { label: "תמונה ראשית", name: "featured_image", widget: "image", required: false }
      - { label: "קטגוריות", name: "categories", widget: "list", required: false }
      - { label: "תגיות", name: "tags", widget: "list", required: false }
      - { label: "שם המחבר", name: "author", widget: "string", required: false, default: "nh local" }
      - { label: "גוף הפוסט", name: "body", widget: "markdown", required: true }