title: "הבלוג של NHLOCAL"
description: "לגלות דברים חדשים זה קל!"
author: "nh local"
email: "nh.local11@gmail.com"
url: "https://blog.ze-kal.top"
baseurl: ""

lang: "he"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

sass:
  sass_dir: _sass
  style: compressed

# Tell Jekyll to include the admin folder in the final build
include:
  - admin

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

custom_settings:
  profile_image: "https://nhlocal.github.io/NH.LOCAL.jpg"
  posts_per_page_home: 5
  recent_posts_sidebar_count: 5
  # Social links moved to _data/social.yml

# Added Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-sitemap

# Minifier settings
jekyll-minifier:
  uglifier_args:
    harmony: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/