# שם תהליך העבודה
name: Build and Deploy Jekyll Site with Pagefind

on:
  push:
    branches:
      - jekyll
  workflow_dispatch:

# --- התיקון המרכזי כאן ---
# שינינו את הרשאות התוכן ל-write כדי לאפשר push
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Remove Gemfile.lock to allow for cross-platform builds
        run: rm -f Gemfile.lock

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          working-directory: ./docs

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Pagefind
        run: npm install -g pagefind

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Run Pagefind to create search index
        run: pagefind --site "_site"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_site
          destination_dir: ./docs
          cname: blog.ze-kal.top